name: CodeNarc Lint Check

on:
  pull_request:
    branches:
      - main
      - develop

jobs:
  codenarc:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Install xmllint
        run: sudo apt-get update && sudo apt-get install -y libxml2-utils

      - name: Get Changed Groovy Files
        id: changed_files
        uses: tj-actions/changed-files@v44
        with:
          files: '**/*.groovy'

      - name: Check if Groovy Files Changed
        id: check_files
        run: |
          if [[ -z "${{ steps.changed_files.outputs.all_changed_files }}" ]]; then
            echo "No Groovy files changed, skipping CodeNarc."
            echo "skip=true" >> $GITHUB_ENV
          else
            echo "skip=false" >> $GITHUB_ENV
            echo "${{ steps.changed_files.outputs.all_changed_files }}" > changed_files.txt
          fi

      - name: Run CodeNarc on Changed Files
        if: env.skip != 'true'
        run: |
          ./gradlew codenarcMain --include "$(cat changed_files.txt | tr '\n' ',')"
        continue-on-error: true

      - name: Parse CodeNarc Violations
        id: parse_violations
        if: env.skip != 'true'
        run: |
          if [ -f build/reports/codenarc/main.xml ]; then
            xmllint --xpath '//File' build/reports/codenarc/main.xml | \
            sed -nE 's/.*<File name="([^"]+)".*/\1/p' > file-names.txt
          
            xmllint --xpath '//Violation' build/reports/codenarc/main.xml | \
            sed -nE 's/.*lineNumber="([^"]+)".*<Message><!\[CDATA\[(.*)\]\]><\/Message>.*/\1:\2/p' > violations.txt
          
            paste -d ":" file-names.txt violations.txt > codenarc-violations.txt || true
          else
            touch codenarc-violations.txt
          fi

          # Filter violations to only include changed files
          grep -Ff changed_files.txt codenarc-violations.txt > filtered-violations.txt || true

          # Store violations content as output
          violations_content=$(cat filtered-violations.txt | base64 -w 0 || echo "")
          echo "violations-content=${violations_content}" >> "$GITHUB_ENV"

      - name: Comment on PR with Violations or Success
        uses: actions/github-script@v7
        env:
          VIOLATIONS: ${{ env.violations-content }}
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const { owner, repo } = context.repo;
            const prNumber = context.payload.pull_request.number;
            const violations = Buffer.from(process.env.VIOLATIONS, 'base64').toString('utf8').split('\n').filter(Boolean);

            if (violations.length > 0) {
              let comments = [];
              for (const violation of violations) {
                const parts = violation.split(":");
                if (parts.length >= 3) {
                  const [file, line, ...messageParts] = parts;
                  const message = messageParts.join(":").trim();

                  comments.push({
                    path: file,
                    line: parseInt(line, 10),
                    body: `⚠️ **CodeNarc Warning:** ${message}`
                  });
                }
              }

              if (comments.length > 0) {
                github.rest.pulls.createReview({
                  owner,
                  repo,
                  pull_number: prNumber,
                  event: "COMMENT",
                  comments
                });
              }
            } else {
              github.rest.issues.createComment({
                owner,
                repo,
                issue_number: prNumber,
                body: "✅ **CodeNarc Check Passed!** No issues detected."
              });
            }
